#cloud-config

timezone: Asia/Tokyo
locale: ja_JP.utf8

repo_update: true
repo_upgrade: all

users:
  - default
  - name: charlotte
  - gecos: Charlotte.J.Ikurumi
  - sudo:  ALL=(ALL) NOPASSWD:ALL
  - ssh_pwauth: False
  - ssh_authorized_keys:
    - XXXXXX
